# docker-compose.traefik.yml
# Configuración adicional para usar con Traefik
# Uso: docker-compose -f docker-compose.yml -f docker-compose.traefik.yml up -d

services:
  backend:
    ports: []  # Remover puertos expuestos cuando usa Traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alugueis-backend.rule=Host(`${BACKEND_DOMAIN}`)"
      - "traefik.http.routers.alugueis-backend.entrypoints=websecure"
      - "traefik.http.routers.alugueis-backend.tls.certresolver=cloudflare"
      - "traefik.http.services.alugueis-backend.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik"
      # Middleware para CORS
      - "traefik.http.middlewares.alugueis-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.alugueis-cors.headers.accesscontrolalloworiginlist=https://${FRONTEND_DOMAIN}"
      - "traefik.http.middlewares.alugueis-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.alugueis-cors.headers.addvaryheader=true"
      - "traefik.http.routers.alugueis-backend.middlewares=alugueis-cors@docker"

  frontend:
    ports: []  # Remover puertos expuestos cuando usa Traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alugueis-frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.alugueis-frontend.entrypoints=websecure"
      - "traefik.http.routers.alugueis-frontend.tls.certresolver=cloudflare"
      - "traefik.http.services.alugueis-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
      # Middleware para headers de seguridad
      - "traefik.http.middlewares.alugueis-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.alugueis-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.alugueis-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.alugueis-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.alugueis-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.alugueis-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.alugueis-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.alugueis-headers.headers.stsSeconds=31536000"
      - "traefik.http.routers.alugueis-frontend.middlewares=alugueis-headers@docker"
